config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  devise_for :users, only: [ :sessions ]
  devise_scope :user do
    get "users/sign_up", to: "devise/registrations#new", as: :new_user_registration
    post "users/", to: "devise/registrations#create", as: :user_registration
  end


  get "games_of_life" => "games_of_life#index", as: :gol_index
  post "games_of_life/upload_file" => "games_of_life#post_file_gol", as: :post_file_gol
  post "games_of_life/random_gol" => "games_of_life#post_random_gol", as: :post_random_gol
  post "games_of_life/next_generation" => "games_of_life#post_next_generation", as: :post_next_generation
  root "games_of_life#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/games_of_life_controller.rb
class GamesOfLifeController < ApplicationController
end
class GamesOfLifeController < ApplicationController
  before_action :authenticate_user!, except: [ :index ]

  def index
  end

  def post_file_gol
    begin
      file = file_post_params
      handle_file_upload file
    rescue ActionController::ParameterMissing
      @message = "File is required"
      respond_to do |format|
        format.turbo_stream { render "error_msg", status: 406 }
      end
      return
    rescue GameOfLife::FileValidationError => e
      @message = e.message
      respond_to do |format|
        format.turbo_stream { render "error_msg", status: 406 }
      end
      return
    end
    respond_to do |format|
      format.turbo_stream
    end
  end

  def post_random_gol
    @game_state = GameOfLife::GameState.random
    respond_to do |format|
      format.turbo_stream { render "post_file_gol" }
    end
  end

  def post_next_generation
    generation = params[:generation].to_i
    rows = params[:rows].to_i
    columns = params[:columns].to_i
    grid = params[:layed_down_grid].split(";").map do |row|
      row.chars.map { |ch| GameOfLife::Cell.new ch }
    end
    @game_state = GameOfLife::GameState.new generation, rows, columns, grid
    @game_state.next_generation!
    respond_to do |format|
      format.turbo_stream
    end
  end

  private
  def handle_file_upload(file)
    @game_state = GameOfLife::GameState.new file.tempfile
  end

  def file_post_params
    params.require(:state_file)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      redirect_to new_user_session_path
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_of_life_helper.rb
module GamesOfLifeHelper
end

app/views/games_of_life/_error_msg.html.erb
  <div id="file_err_msg">
    <%= @message %>
  </div>

app/views/games_of_life/_form.html.erb
<%= form_with id: "form_play", data: { play_target: "form" }, url: post_next_generation_path do |form| %>
  <div class="flex flex-col gap-2">
    <div>
      Generation <%= @game_state.generation %>:
      <%=form.text_field :generation, value: @game_state.generation, hidden: true %>
    </div>
    <div>
      <%= @game_state.rows %> <%= @game_state.columns %>
      <%=form.text_field :rows, value: @game_state.rows, hidden: true %>
      <%=form.text_field :columns, value: @game_state.columns, hidden: true %>
    </div>
    <%=form.text_field :layed_down_grid, value: @game_state.lay_down_grid, hidden: true %>
    <table>
      <tbody>
        <% @game_state.grid.each_with_index do |row, i| %>
          <tr>
            <% row.each_with_index do |cell, j| %>
              <% cell_color = cell.is_alive? ? 'black' : 'white' %>
              <td style="width: 10px; height: 10px; background: <%= cell_color %>; border: solid 1px black">
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= form.submit "submit", hidden: true, id: "submit_btn", data: {play_target: "sub"} %>
  </div>
<% end %>

app/views/games_of_life/_logged_in.html.erb
<div class="grid grid-cols-2 gap-8 w-full">
  <div class="col-span-2 lg:col-span-1 enclosed">
    <%= form_with method: :post, url: post_file_gol_path, multipart: true, class: "flex flex-col gap-2" do |form| %>
      <%= render "games_of_life/error_msg" %>
      <div>
        <%= form.label :state_file %>
        <%= file_field_tag :state_file, id: "file_upload"  %>
      </div>
      <div>
        <%= button_tag "Submit", class: "btn" %>
      </div>
    <% end %>
  </div>
  <div class="col-span-2 lg:col-span-1 enclosed">
    <%= form_with method: :post, url: post_random_gol_path, multipart: true do |form| %>
      <%= button_tag "Generate random", class: "btn" %>
    <% end %>
  </div>
  <div class="col-span-2 enclosed">
    <%= turbo_frame_tag "grid_turbo_frame_tag" do %>
      Here goes the game of life :)
    <% end %>
  </div>
</div>

app/views/games_of_life/_not_logged_in.html.erb
<div class="grid grid-cols-2 gap-8 w-full">
  <div class="col-span-2 lg:col-span-1 enclosed">
    Log in to start Game Of Life
  </div>
  <div class="col-span-2 lg:col-span-1 enclosed flex flex-row gap-4">
    <%= link_to "Log in", new_user_session_path, class: "btn w-full" %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn w-full" %>
  </div>
</div>

app/views/games_of_life/error_msg.turbo_stream.erb
<%= turbo_stream.replace "file_err_msg" do %>
  <%= render "games_of_life/error_msg" %>
<% end %>

app/views/games_of_life/index.html.erb
<% if user_signed_in? %>
  <%= render "games_of_life/logged_in" %>
<% else %>
  <%= render "games_of_life/not_logged_in" %>
<% end %>

app/views/games_of_life/post_file_gol.turbo_stream.erb
  <%= turbo_stream.replace "grid_turbo_frame_tag" do %>
  <%= turbo_frame_tag "grid_turbo_frame_tag" do %>
    <div data-controller="play" class="grid grid-cols-6 justify-center gap-2">
      <div class="flex flex-col gap-4 p-8 mb-8 col-span-6 lg:col-span-2">
        <h3 class="text-lg font-semibold">Legend</h3>
        <div class="flex flex-row gap-4 justify-start">
          <div class="w-12 h-12 bg-black border border-black"></div>
          <div>Alive cell</div>
        </div>
        <div class="flex flex-row gap-4 justify-start">
          <div class="w-12 h-12 bg-white border border-black"></div>
          <div>Dead cell</div>
        </div>
        <button id="play-button" data-action="click->play#togglePlay" data-play-target="button" class="mt-8 rounded-lg bg-slate-600 text-white px-8 py-4 text-lg">
          >
        </button>
      </div>
      <div class="flex flex-row justify-center gap col-span-6 lg:col-span-4">
        <%= turbo_frame_tag "canvas" do %>
          <%= render "games_of_life/form" %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>
<%= turbo_stream.replace "file_err_msg" do %>
  <div id="file_err_msg">
  </div>
<% end %>

app/views/games_of_life/post_next_generation.turbo_stream.erb
<%= turbo_stream.replace "canvas" do %>
  <%= turbo_frame_tag "canvas" do %>
    <%= render "games_of_life/form" %>
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="sm:fixed sm:top-0 w-screen sm:h-24 shadow-sm text-white bg-slate-800 flex flex-row justify-between gap-4 p-8 items-center">
  <%= link_to root_path, title: "Game Of Life - Home" do %>
  <div>
    <h1 class="text-4xl font-bold">
      Game Of Life
    </h1>
    <h2 class="text-lg font-semibold">
      Built with Ruby on Rails
    </h2>
  </div>
  <% end %>
  <ul class="flex flex-row justify-between gap-4 items-center">
    <% if user_signed_in? %>
      <li>
        Welcome <%= current_user.email %>
      </li>
      <li class="hover:font-bold" >
        <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "Sign in", new_user_session_path %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Ror Gol" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container mx-auto mt-4 px-5 flex flex-col gap-8 sm:mt-28 ">
      <% if notice then %>
        <p class="notice"><%= notice %></p>
      <% end %>
      <% if alert then %>
        <p class="alert"><%= alert %></p>
      <% end %>
    </div>
    <main class="container mx-auto mt-4 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>